# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FOLIO Developer
description: >
  FOLIO is a new open source, cloud hostable, app-store based
  library platform, designed to facilitate collaboration between
  disparate development teams.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dev.folio.org" # the base hostname & protocol for your site
google_analytics: UA-79833310-3

# Build settings
remote_theme: Balancingrock/classic-jekyll-theme@1.9.4
markdown: kramdown
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-gist

exclude: [bin, Gemfile, Gemfile.lock, CONTRIBUTING.md, README.md, tmp, vendor, work]

collections:
  posts:
    permalink: /news/:year/:month/:day/:title/
